backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

display_url: https://gatsby-netlify-cms-example.netlify.com/

collections:
  - name: "projects"
    label: "Projects"
    description: "Projects I've worked on."
    folder: "src/data/collections/projects"
    create: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "meetup" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Start", name: "start", widget: "datetime" }
      - { label: "End", name: "end", widget: "datetime" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/data/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "About heading", name: "aboutHeader", required: true, widget: "string" }
          - { label: "About body", name: "aboutBody", required: true, widget: "string" }
          - { label: "Projects heading", name: "projectsHeader", required: true, widget: "string" }
          - { label: "Contact heading", name: "contactHeader", required: true, widget: "string" }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
  - name: "navbarAndFooter"
    label: "Navbar & Footer"
    files:
      - file: "src/data/pages/components/navbar/index.md"
        label: "Navbar"
        name: "navbar"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "navbar" }
          - { label: "Menu Items",
              name: "menuItems",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Link Type", name: "linkType", widget: "select", options: ["internal", "external"] },
                  { label: "Link URL", name: "linkURL", widget: "string", hint: "Use a relative URL (e.g. /about) if the link is an internal link." },
                ],
            }
      - file: "src/data/pages/components/header/index.md"
        label: "Header"
        name: "header"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "header" }
          - { label: "Title", name: "title", widget: "string", required: true}
          - { label: "Subtitle", name: "subTitle", widget: "string", required: true}
          - { label: "Header image",
              name: "headerImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" }
                ],
             }
      - file: "src/data/pages/components/footer/index.md"
        label: "Footer"
        name: "footer"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "footer" }
          - { label: "Title", name: "title", widget: "string", required: true}